import type { TechName } from '../types/index';

export const iconMap: Record<TechName, string> = {
    'Javascript': 'javascript',
    'Typescript': 'typescript',
    'React.js': 'react',
    'Next.js': 'nextjs',
    'Node.js': 'nodejs',
    'Socket.IO': 'socketio',
    'Docker': 'docker',
    'Jest': 'jest',
    'Redux': 'redux',
    'TanStack Query': 'tanstack-query',
    'Zustand': 'zustand',
    'MongoDB': 'mongodb',
    'PostgreSQL': 'postgresql',
    'My SQL': 'mysql',
    'Firebase': 'firebase',
    'Java': 'java',
    'Python': 'python',
    'Angular': 'angular',
    'Ionic': 'ionic',
    'GIT': 'git',
    'GitHub': 'github',
    'Sass': 'sass',
    'Styled Components': 'styled-components',
    'Bootstrap': 'bootstrap',
    'TailwindCSS': 'tailwindcss',
    'Figma': 'figma',
    'Photoshop': 'photoshop',
    'Mongoose': 'mongoose_logo',
    'Emotion': 'emotion_logo',
    'Vite': 'vite',
    'Express': 'express',
};
